### ISSUE TITLE
How you fix the sleep?

### ISSUE THREAD

**Issue by Pequem** [akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build#6]
I build my OpenCore with the guild to learn and update all and my pc doesn't come back from sleep. My screen still black

**Comment by nadhirfr** [comment]
Hello @Pequem ,
Do you have any update on this?

I have the same issue, HDMI and DVI black screen after wake up from sleep. Display port is working fine, only HDMI and DVI. HDMI will show display after turn off then turn on again the monitor. I'm using i5 10400 iGPU Intel UHD 630

**Comment by Pequem** [comment]
it is a parameter in the opencore configuration file that I had to change, I don’t remember what it is, what I did was take the file that I created by the opencore tutorial and compared it with the file in that repository and was testing it.

**Comment by Pequem** [comment]
maybe can be this:

"iGPU wake is partially broken due to numerous hacks apple uses in AppleGraphicsPowerManagement.kext with real Macs, to get around this you'll likely need igfxonln=1 to force all displays online. Obviously test first to make sure you have this issue."



https://dortania.github.io/OpenCore-Post-Install/universal/sleep.html#fixing-gpus

**Comment by akarsh1995** [comment]
@Pequem I had and the plist in the repo has this feature on. [sample.plist](https://github.com/akarsh1995/ASUS-TUF-Gaming-B460-Plus-i5-10400-Opencore-Hackintosh-Build/blob/dd152de4f58f2d0f69f19d0dfc0ba8b0a7572c1e/OC/sample_config.plist#L834)

**Comment by nadhirfr** [comment]
Cool! It's now fixed with **igfxonln=1** 
Thanks a lot @Pequem @akarsh1995
